# Generated by Django 4.0.3 on 2022-06-21 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Катерогії',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Назва')),
                ('photo', models.ImageField(upload_to='photos/&Y/%m/&d/', verbose_name='Фото')),
                ('price', models.IntegerField(db_index=True, verbose_name='Ціна')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.category')),
            ],
            options={
                'verbose_name': 'Одежа',
                'verbose_name_plural': 'Одежі',
            },
        ),
    ]
